// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiColumnsByIdData, DeleteApiColumnsByIdResponses, DeleteApiRowsByIdData, DeleteApiRowsByIdResponses, DeleteApiTablesByIdData, DeleteApiTablesByIdResponses, GetApiTablesByIdData, GetApiTablesByIdErrors, GetApiTablesByIdResponses, GetApiTablesData, GetApiTablesResponses, PatchApiColumnsByIdData, PatchApiColumnsByIdErrors, PatchApiColumnsByIdResponses, PatchApiColumnsReorderData, PatchApiColumnsReorderResponses, PatchApiRowsReorderData, PatchApiRowsReorderResponses, PostApiColumnsData, PostApiColumnsResponses, PostApiRowsData, PostApiRowsResponses, PostApiTablesData, PostApiTablesErrors, PostApiTablesResponses, PutApiRowsByRowIdValuesData, PutApiRowsByRowIdValuesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get all tables
 */
export const getApiTables = <ThrowOnError extends boolean = true>(options?: Options<GetApiTablesData, ThrowOnError>) => (options?.client ?? client).get<GetApiTablesResponses, unknown, ThrowOnError>({ url: '/api/tables', ...options });

/**
 * Create a table
 */
export const postApiTables = <ThrowOnError extends boolean = true>(options?: Options<PostApiTablesData, ThrowOnError>) => (options?.client ?? client).post<PostApiTablesResponses, PostApiTablesErrors, ThrowOnError>({
    url: '/api/tables',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete a table
 */
export const deleteApiTablesById = <ThrowOnError extends boolean = true>(options?: Options<DeleteApiTablesByIdData, ThrowOnError>) => (options?.client ?? client).delete<DeleteApiTablesByIdResponses, unknown, ThrowOnError>({ url: '/api/tables/{id}', ...options });

/**
 * Get table with rows and columns
 */
export const getApiTablesById = <ThrowOnError extends boolean = true>(options?: Options<GetApiTablesByIdData, ThrowOnError>) => (options?.client ?? client).get<GetApiTablesByIdResponses, GetApiTablesByIdErrors, ThrowOnError>({ url: '/api/tables/{id}', ...options });

/**
 * Add a column to a table
 */
export const postApiColumns = <ThrowOnError extends boolean = true>(options?: Options<PostApiColumnsData, ThrowOnError>) => (options?.client ?? client).post<PostApiColumnsResponses, unknown, ThrowOnError>({
    url: '/api/columns',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Reorder columns
 */
export const patchApiColumnsReorder = <ThrowOnError extends boolean = true>(options?: Options<PatchApiColumnsReorderData, ThrowOnError>) => (options?.client ?? client).patch<PatchApiColumnsReorderResponses, unknown, ThrowOnError>({
    url: '/api/columns/reorder',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete a column
 */
export const deleteApiColumnsById = <ThrowOnError extends boolean = true>(options?: Options<DeleteApiColumnsByIdData, ThrowOnError>) => (options?.client ?? client).delete<DeleteApiColumnsByIdResponses, unknown, ThrowOnError>({ url: '/api/columns/{id}', ...options });

/**
 * Update a column
 */
export const patchApiColumnsById = <ThrowOnError extends boolean = true>(options?: Options<PatchApiColumnsByIdData, ThrowOnError>) => (options?.client ?? client).patch<PatchApiColumnsByIdResponses, PatchApiColumnsByIdErrors, ThrowOnError>({
    url: '/api/columns/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Add a row to a table
 */
export const postApiRows = <ThrowOnError extends boolean = true>(options?: Options<PostApiRowsData, ThrowOnError>) => (options?.client ?? client).post<PostApiRowsResponses, unknown, ThrowOnError>({
    url: '/api/rows',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Reorder rows
 */
export const patchApiRowsReorder = <ThrowOnError extends boolean = true>(options?: Options<PatchApiRowsReorderData, ThrowOnError>) => (options?.client ?? client).patch<PatchApiRowsReorderResponses, unknown, ThrowOnError>({
    url: '/api/rows/reorder',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete a row
 */
export const deleteApiRowsById = <ThrowOnError extends boolean = true>(options?: Options<DeleteApiRowsByIdData, ThrowOnError>) => (options?.client ?? client).delete<DeleteApiRowsByIdResponses, unknown, ThrowOnError>({ url: '/api/rows/{id}', ...options });

/**
 * Upsert a cell value
 */
export const putApiRowsByRowIdValues = <ThrowOnError extends boolean = true>(options?: Options<PutApiRowsByRowIdValuesData, ThrowOnError>) => (options?.client ?? client).put<PutApiRowsByRowIdValuesResponses, unknown, ThrowOnError>({
    url: '/api/rows/{rowId}/values',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});
