// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type GetApiTablesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tables';
};

export type GetApiTablesResponses = {
    /**
     * List of tables
     */
    200: Array<{
        id: number;
        name: string;
        createdAt?: string | null;
    }>;
};

export type GetApiTablesResponse = GetApiTablesResponses[keyof GetApiTablesResponses];

export type PostApiTablesData = {
    body?: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/tables';
};

export type PostApiTablesErrors = {
    /**
     * Validation error
     */
    400: {
        error: string;
    };
};

export type PostApiTablesError = PostApiTablesErrors[keyof PostApiTablesErrors];

export type PostApiTablesResponses = {
    /**
     * Created table
     */
    201: {
        id: number;
        name: string;
        createdAt?: string | null;
    };
};

export type PostApiTablesResponse = PostApiTablesResponses[keyof PostApiTablesResponses];

export type DeleteApiTablesByIdData = {
    body?: never;
    path?: {
        id?: number | null;
    };
    query?: never;
    url: '/api/tables/{id}';
};

export type DeleteApiTablesByIdResponses = {
    /**
     * Deleted
     */
    200: {
        ok: true;
    };
};

export type DeleteApiTablesByIdResponse = DeleteApiTablesByIdResponses[keyof DeleteApiTablesByIdResponses];

export type GetApiTablesByIdData = {
    body?: never;
    path?: {
        id?: number | null;
    };
    query?: never;
    url: '/api/tables/{id}';
};

export type GetApiTablesByIdErrors = {
    /**
     * Not found
     */
    404: {
        error: string;
    };
};

export type GetApiTablesByIdError = GetApiTablesByIdErrors[keyof GetApiTablesByIdErrors];

export type GetApiTablesByIdResponses = {
    /**
     * Full table data
     */
    200: {
        id: number;
        name: string;
        createdAt?: string | null;
        columns: Array<{
            id: number;
            name: string;
            type: 'text' | 'number' | 'select' | 'toggle' | 'date';
            visible: boolean;
            options: Array<{
                id: number;
                label: string;
                color: string | null;
                order: number;
                columnId: number;
            }>;
        }>;
        rows: Array<{
            id: number;
            order: number;
            createdAt?: string | null;
            values: Array<{
                id: number;
                rowId: number;
                columnId: number;
                value: string | null;
            }>;
        }>;
    };
};

export type GetApiTablesByIdResponse = GetApiTablesByIdResponses[keyof GetApiTablesByIdResponses];

export type PostApiColumnsData = {
    body?: {
        tableId: number;
        name: string;
        type: 'text' | 'number' | 'select' | 'toggle' | 'date';
        options?: Array<{
            label: string;
            color?: string;
        }>;
    };
    path?: never;
    query?: never;
    url: '/api/columns';
};

export type PostApiColumnsResponses = {
    /**
     * Created column
     */
    201: {
        id: number;
        name: string;
        type: 'text' | 'number' | 'select' | 'toggle' | 'date';
        visible: boolean;
        options: Array<{
            id: number;
            label: string;
            color: string | null;
            order: number;
            columnId: number;
        }>;
    };
};

export type PostApiColumnsResponse = PostApiColumnsResponses[keyof PostApiColumnsResponses];

export type PatchApiColumnsReorderData = {
    body?: {
        orderedIds: Array<number>;
    };
    path?: never;
    query?: never;
    url: '/api/columns/reorder';
};

export type PatchApiColumnsReorderResponses = {
    /**
     * Reordered
     */
    200: {
        ok: true;
    };
};

export type PatchApiColumnsReorderResponse = PatchApiColumnsReorderResponses[keyof PatchApiColumnsReorderResponses];

export type DeleteApiColumnsByIdData = {
    body?: never;
    path?: {
        id?: number | null;
    };
    query?: never;
    url: '/api/columns/{id}';
};

export type DeleteApiColumnsByIdResponses = {
    /**
     * Deleted
     */
    200: {
        ok: true;
    };
};

export type DeleteApiColumnsByIdResponse = DeleteApiColumnsByIdResponses[keyof DeleteApiColumnsByIdResponses];

export type PatchApiColumnsByIdData = {
    body?: {
        name?: string;
        visible?: boolean;
        order?: number;
    };
    path?: {
        id?: number | null;
    };
    query?: never;
    url: '/api/columns/{id}';
};

export type PatchApiColumnsByIdErrors = {
    /**
     * No fields to update
     */
    400: {
        error: string;
    };
};

export type PatchApiColumnsByIdError = PatchApiColumnsByIdErrors[keyof PatchApiColumnsByIdErrors];

export type PatchApiColumnsByIdResponses = {
    /**
     * Updated
     */
    200: {
        ok: true;
    };
};

export type PatchApiColumnsByIdResponse = PatchApiColumnsByIdResponses[keyof PatchApiColumnsByIdResponses];

export type PostApiRowsData = {
    body?: {
        tableId: number;
    };
    path?: never;
    query?: never;
    url: '/api/rows';
};

export type PostApiRowsResponses = {
    /**
     * Created row
     */
    201: {
        id: number;
        order: number;
        createdAt?: string | null;
        values: Array<{
            id: number;
            rowId: number;
            columnId: number;
            value: string | null;
        }>;
    };
};

export type PostApiRowsResponse = PostApiRowsResponses[keyof PostApiRowsResponses];

export type PatchApiRowsReorderData = {
    body?: {
        orderedIds: Array<number>;
    };
    path?: never;
    query?: never;
    url: '/api/rows/reorder';
};

export type PatchApiRowsReorderResponses = {
    /**
     * Reordered
     */
    200: {
        ok: true;
    };
};

export type PatchApiRowsReorderResponse = PatchApiRowsReorderResponses[keyof PatchApiRowsReorderResponses];

export type DeleteApiRowsByIdData = {
    body?: never;
    path?: {
        id?: number | null;
    };
    query?: never;
    url: '/api/rows/{id}';
};

export type DeleteApiRowsByIdResponses = {
    /**
     * Deleted
     */
    200: {
        ok: true;
    };
};

export type DeleteApiRowsByIdResponse = DeleteApiRowsByIdResponses[keyof DeleteApiRowsByIdResponses];

export type PutApiRowsByRowIdValuesData = {
    body?: {
        columnId: number;
        value: string;
    };
    path?: {
        rowId?: number | null;
    };
    query?: never;
    url: '/api/rows/{rowId}/values';
};

export type PutApiRowsByRowIdValuesResponses = {
    /**
     * Upserted
     */
    200: {
        ok: true;
    };
};

export type PutApiRowsByRowIdValuesResponse = PutApiRowsByRowIdValuesResponses[keyof PutApiRowsByRowIdValuesResponses];
